CREATE DATABASE authdb;
CREATE DATABASE profiledb;


USE authdb;

CREATE TABLE IF NOT EXISTS auth_users (
	id VARCHAR(36) PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	role VARCHAR(50),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

USE profiledb

CREATE TABLE IF NOT EXISTS profiles (
	
	id VARCHAR(36) PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	name VARCHAR(255),
	bio TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);